using NUnit.Framework;

namespace Problems
{
    [TestFixture]
    public class Problem002
    {
        [Test]
        public void Test()
        {
            // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
            // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

            int sumOfEvens = 0;

            int i = 1;
            int j = 2;
            while (i < 4000000)
            {
                if (i%2 == 0)
                {
                    sumOfEvens += i;
                }

                int temp = j;
                j = i + j;
                i = temp;
            }

            Assert.Inconclusive(sumOfEvens.ToString());
        }

    }
}